### ISSUE TITLE
Project Checklist for the ALPHA

### ISSUE THREAD

**Issue by AlexRoijals** [AlexRoijals/ProjectWormhole#78]
This is a list with the whole compilation of issues of the alpha (18/12/2017) to serve us for reference.

**EXPECTED RESULT:**
_Each one of this elements has its respective issue/GitHub ID assigned and that's what should be completed and expected._

**DESIGN**
- [x] Game​ ​Design​ ​Document​ ​(GDD)​ ​[GitHub​ ​Wiki]
_Usar índice de Wiki en GitHub, debe incluir Introducción, Mecánicas, Level Flow..._
- [x] Level​ ​Design​ ​Map​ ​[GitHub​ ​>​ ​WikiResources/level_design_map.png]​ ​(max.​ ​4096x4096​ ​px)
_Detallado y leyenda con todos los elementos de gameplay._
- [x] Concept​ ​Art​ ​characters​ ​and​ ​environment​ ​[GitHub​ ​>​ ​ConceptArt]
_Debidamente presentado con background y logo en cada imagen._
- [x] Character​ ​Thumbnails​ ​[GitHub​ ​>​ ​ConceptArt/character_thumbnails.png]
_Mínimo 12 siluetas de player/personajes/enemigos_
- [x] Props​ ​Thumbnails​ ​[GitHub​ ​>​ ​ConceptArt/props_thumbnails.png]
_Mínimo 12 siluetas de props/buildings/elementos del nivel_
- [x] Characters​ ​size​ ​chart​ ​[GitHub​ ​>​ ​ConceptArt/characters_size_chart.png]
_Imagen comparativa tamaños personaje y enemigos, puede utilizar thumbnails_
- [x] Level​ ​props​ ​size​ ​chart​ ​[GitHub​ ​>​ ​ConceptArt/props_size_chart.png]
_Imagen comparativa tamaños elementos escenario, puede utilizar thumbnails_
- [x] Level​ ​flow​ ​map​ ​[GitHub​ ​>​ ​WikiResources/level_flow_map.png]
_Diferentes acciones que se tiene que realizar el jugador para superar nivel_
- [x] Screens​ ​mockups​ ​[GitHub​ ​>​ ​Mockups]
_Mínimo 1x TITLE, 2x GAMEPLAY, 1x ENDING_

**GENERAL**
- [x] GENERAL​ ​Fase​ ​1:​ ​Animación​ ​transición​ ​entre​ ​escenas:​ ​fade-In​ ​/​ ​fade-out​ ​u​ ​otra​ ​animación.
- [x] GENERAL​ ​Fase​ ​2:​ ​Modo​ ​GOD​ ​implementado:​ ​F10​ ​(salto​ ​de​ ​stages,​ ​inmunidad,​ ​volar)
- [x] GENERAL​ ​Fase​ ​3:​ ​Implementar​ ​condiciones​ ​de​ ​victoria​ ​y​ ​derrota.

**SCREEN: LOGO**
- [x] LOGO​ ​Fase​ ​1:​ ​Animación​ ​de​ ​entrada/aparición​ ​(fading,​ ​movimiento...)

**SCREEN: TITLE**
- [x] TITLE​ ​Fase​ ​1:​ ​Título​ ​del​ ​juego​ ​con​ ​ARTE​ ​FINAL​ ​e​ ​implementado
- [x] TITLE​ ​Fase​ ​2:​ ​Animación​ ​de​ ​entrada/aparición​ ​del​ ​título​ ​(fading,​ ​movimiento...)
- [x] MENU​ ​Fase​ ​1:​ ​Menú​ ​básico​ ​de​ ​juego:​ ​GAME​ ​START​ ​-​ ​OPTIONS​ ​-​ ​EXIT

**SCREEN: OPTIONS**
- [x] OPTIONS​ ​Fase​ ​1:​ ​Opciones​ ​básicas​ ​configuración​ ​de​ ​juego
       - OP1:​ ​Selección​ ​de​ ​resolución:​ ​1280x720​ ​(default)​ ​-​ ​1600x1200​ ​-​ ​1920x1080
       - OP2:​ ​Selección​ ​de​ ​calidad:​ ​FAST​ ​-​ ​GOOD​ ​-​ ​FANTASTIC​ ​-​ ​ULTRA

**SCREEN: GAMEPLAY (Main Level)**
- [x] NIVEL​ ​Fase​ ​1:​ ​Mecánicas​ ​básicas​ ​del​ ​juego​ ​FUNCIONALES​ ​y​ ​TESTEABLES
- [x] NIVEL​ ​Fase​ ​2:​ ​Modelado​ ​temporal​ ​(puede​ ​utilizar​ ​boxes)
- [x] PROPS​ ​Fase​ ​1:​ ​8​ ​props​ ​finales​ ​implementados​ ​en​ ​nivel​ ​(TOTAL:​ ​8​ ​props)
       - Standard Book [https://github.com/AlexRoijals/ProjectWormhole/issues/76](url)
       - Hair ornament [https://github.com/AlexRoijals/ProjectWormhole/issues/77](url)
       - Farewell letter [https://github.com/AlexRoijals/ProjectWormhole/issues/75](url)
       - Drugs
       - Celluloid Film
       - Flowers
       - Hair ornament
       - Umbilical cord
       - Mandolin
       - Map
       - Standard House [https://github.com/AlexRoijals/ProjectWormhole/issues/48](url)
       - Town Hall [https://github.com/AlexRoijals/ProjectWormhole/issues/50](url)
- [x] PLAYER​ ​Fase​ ​1:​ ​Modelado​ ​final​ ​+​ ​texturizado​ ​temporal​ ​(diffuse)
- [x] NPC​ ​A​ ​Fase​ ​1:​ ​Modelado​ ​final​ ​+​ ​texturizado​ ​temporal​ ​(diffuse)
       _Model of Anju Character_
- [x] BOSS/NPC​ ​Fase​ ​1:​ ​Modelado​ ​temporal​ ​(puede​ ​utilizar​ ​boxes)
        _Model of the Worm_
- [x] PAUSE​ ​Fase​ ​1:​ ​Opción​ ​de​ ​PAUSA​ ​implementada
- [x] INTERFAZ​ ​Fase​ ​1:​ ​Elementos​ ​básicos​ ​(provisionales)​ ​de​ ​interfaz​ ​(GUI)
- [x] INPUTS​ ​Fase​ ​1:​ ​Controles​ ​(provisionales)​ ​keyboard​ ​y​ ​mouse
- [x] PARTÍCULAS​ ​Fase​ ​1:​ ​5​ ​sistemas​ ​de​ ​partículas​ ​(TOTAL:​ ​5​ ​particles-fx)
        [https://github.com/AlexRoijals/ProjectWormhole/issues/55](url)
- [x] SOUNDS​ ​Fase​ ​1:​ ​5​ ​sonidos​ ​implementados​ ​(TOTAL:​ ​5​ ​sonidos​ ​fx)
        [https://github.com/AlexRoijals/ProjectWormhole/issues/62](url)

**SCREEN: ENDING**
- [x] ENDING​ ​Fase​ ​1:​ ​Custom​ ​background​ ​con​ ​mensaje​ ​de​ ​victoria​ ​y​ ​derrota​ ​básicos.
